# Generated by Django 5.0.3 on 2024-04-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appshop', '0003_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='order',
        ),
    ]
