# Generated by Django 5.0.3 on 2024-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0022_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='age',
            name='agecalc',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
