# Generated by Django 5.0.3 on 2024-05-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0023_age_agecalc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='agecalc',
            field=models.CharField(max_length=200),
        ),
    ]
